#! /bin/sh

setxkbmap us,il -option grp:alt_shift_toggle
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/bspwm/launch.sh

bspc config external_rules_command "$HOME/.config/bspwm/bspwm-external-rules"

bspc monitor -d 1 2 3 4 5 6 

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Google-chrome desktop='^2'
bspc rule -a Soffice desktop='^3'
bspc rule -a discord desktop='^5' 
bspc rule -a Whatsapp-for-linux state=floating desktop='^5' 
bspc rule -a vlc desktop='^4'
bspc rule -a Qalculate-gtk state=floating
bspc rule -a Kite state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
